# Code generate by Gango
FROM golang:1.21-bullseye as builder

WORKDIR /go/src

COPY . .

RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -o /{{.ProjectName}} cmd/base.go
FROM debian:buster-slim

EXPOSE 8000
EXPOSE 9090

COPY --from=builder /{{.ProjectName}} ./
ENTRYPOINT ["./{{.ProjectName}}","serve"]
