# Code generate by Gango
FROM golang:1.20-alpine as base

RUN ["apk","add","make"]

WORKDIR /build
COPY . /build/.

RUN ["make","all"]

FROM base

WORKDIR /app
COPY --from=base /build/{{.ProjectName}} {{.ProjectName}}

RUN ["chmod","+x","{{.ProjectName}}"]

EXPOSE 8000
EXPOSE 9090

ENTRYPOINT ["./{{.ProjectName}}","serve"]
